import './globals.css'
import { Rubik } from 'next/font/google'

// components
import Navbar from './components/Navbar'


// Google Fonts
const rubik = Rubik({ subsets: ['latin'] })


export const metadata = {
  title: 'CLRK Helpdesk',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
